### ISSUE TITLE
[Bug][Windows] Client crashing instead of exiting

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#21] opened 2016-11-01 20:25 UTC
![Screenshot](https://i.imgur.com/6botucL.png)

OS: Microsoft Windows [Version 6.3.9600] x64
Client: 3.1 [Build: 1476720122]

Issue: https://github.com/pathmann/pyTSon/blob/master/generated/pregen/ts3plugin.py#L103

**Comment by pathmann** [comment] 2016-11-01 20:35
Maybe fixed with 4059765cf5023abddf7525d605d980ba62dc7fb3? Please, retest.

Can't reproduce in my vm.

**Comment by Bluscream** [comment] 2016-11-01 20:40
fixed!

**Comment by Bluscream** [comment] 2016-11-01 21:20
```ini
2016-11-01 21:13:03.490971|ERROR   |pyTSon.ts3plugin.processCommandTest|   |TypeError: items() takes no arguments (1 given)
                                                                            
                                                                            During handling of the above exception, another exception occurred:
                                                                            
                                                                            Traceback (most recent call last):
                                                                              File "C:/Users/blusc_000/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\ts3plugin.py", line 259, in callMethod
                                                                                ret.append(meth(*args))
                                                                            SystemError: PyEval_EvalFrameEx returned a result with an error set
```

**Comment by pathmann** [comment] 2016-11-01 22:04
Still can't reproduce. Please retest again with 24ab414cf0f8f7b44aea3ce206ef517ecf764d54.

The exception shows, that on shutdown, the python interpreter gets "confused" (events got still fired, but some objects are already deleted).

**Comment by Bluscream** [comment] 2016-11-19 10:05
https://r4p3.net/threads/c-extended-info-plugin-source.331/page-4#post-33668

**Comment by Metvernichter** [comment] 2016-12-13 05:23
I have the same problem.

**Comment by pathmann** [comment] 2016-12-21 21:12
Please retest with v1.0.5

**Comment by pathmann** [comment] 2017-01-12 02:07
*bump*

**Comment by Bluscream** [comment] 2017-01-12 02:18
I f*cked up my pytson installation. Have to wait till 1.1.0

**Comment by pathmann** [comment] 2017-01-12 02:43
Actually, I want this finally fixed in 1.1.0 (if it's not already fixed with 1.0.5). So I'll compile a temporary windows 64bit release to recheck and upload it here (don't know when).

**Comment by Bluscream** [comment] 2017-01-12 02:48
Nice

**Comment by Bluscream** [comment] 2017-01-12 15:27
Where is the dll?

**Comment by pathmann** [comment] 2017-01-12 16:18
[pyTSon_win64.zip](https://github.com/pathmann/pyTSon/files/702204/pyTSon_win64.zip)

As I said: I didn't know when! But 'when' is actually now.

Please wipe ALL your data from AppData\Roaming\TS3Client\plugins\pyTSon, because from now on, a new directory layout is used.

Furthermore, pyTSon plugins are now accessed as python packages, so you need to create a subdirectory in scripts and place your files there (don't forget a __init__.py).

For the long story, here is the current changelog:

> * the ts3 module got renamed to ts3lib (to not clash with packages on pypi)
* users can now download plugins from online repositories within the app
* plugin developers can maintain their own repository (recommended) or merge directly into the "pyTSon master"
* plugins are no longer restricted to consist of only one file, instead every plugin should be a python package in pyTSon/scripts (if your plugin is one file: create a directory, move your script into it and rename it to __init__.py); repositories can contain zipfiles which will be extracted in the app on installation (if you don't use the pypi-dependency feature of the repository, so deliver dependencies in your package, use relative imports instead of adding your local include directory to sys.path)
* pip is now used for dependency handling
* added an interpreter (no interactive mode)
* Plugin infrastructure overhauled:
    * the python standard library is now located in pyTSon/lib/python3.5
    * pyTSon/include is still the "main include path"
    * plugins are now subdirectories in pyTSon/scripts
    * interpreter python(.exe) added in pyTSon/ (won't run from other directory!)
* added a simple api to query the TeamSpeak 3 client's settings database with ts3client.Config
* added api to work with IconPacks with ts3client.IconPack
* setupUi (and others) will now load icons from an iconpack if widgets contain a dynamic string property called 'pytsonicon' containing the variable to the icon in the iconpack
* config moved to subdirectory; if plugins use configfiles, they should also use this directory
* added convenience functions getConfigPath and getPluginPath (in module pytson) which work like os.path.join with the specific ts3 path prefixed before
* users can now remove plugins within the ui of the app
* if a new version (of the python standard library) is installed, the old one will be removed automatically
* as a result of the above, it is not longer supported to have multiple releases installed (for multiple architectures)
* the example scripts are no longer contained in the install package but can be pulled from the "pyTSon master" repository
* pytsonui.getValues is dropped, plugin developers need to create their own dialog classes


Upgrade tips (adapt the pathes depending on your platform):
    * backup everything in ~/.ts3client/plugins/pyTSon/scripts (except ts3plugin.py)
    * backup your config files, at last pyTSon's config in ~/.ts3client/pyTSon.conf
    * wipe everything in ~/.ts3client/plugins/pyTSon
    * install release 1.1.0
    * copy the config file(s) to ~/.ts3client/pyTSon (mkdir first or start the client once and close again)
    * create a directory for each of your scripts under ~/.ts3client/plugins/pyTSon/scripts, move each script in their subdirectory and rename them to __init__.py or do other pythonic package management

**Comment by Bluscream** [comment] 2017-01-12 16:29
Und wo kommen jetzt externe libraries rein? In lib_new? :D

**Comment by pathmann** [comment] 2017-01-12 16:34
> pyTSon/include is still the "main include path"

"lib_new" will be renamed to "lib" by the c part of pyTSon.

**Comment by Bluscream** [comment] 2017-01-12 16:36
Ok hab mich nur gewundert weil da jz ganz viele header files drin sind :D

**Comment by pathmann** [comment] 2017-01-12 16:54
That's just a prerelease for testing purposes, I did not test anything on windows yet, so this can change in the next public release.

**Comment by Bluscream** [comment] 2017-01-12 16:57
True, but good thing that I have it now and not when its too late and I need to rush to update my scripts folder structures etc.

**Comment by pathmann** [comment] 2017-01-12 17:05
```python
import ts3lib as ts3
``` 
and you are done

**Comment by pathmann** [comment] 2017-01-12 17:07
Before this get out of hand: let's focus on the 'crash instead of exiting' in this issue.

**Comment by Bluscream** [comment] 2017-01-12 17:07
Sure, but I need to get my scripts running first to have a realistic scenario

**Comment by Bluscream** [comment] 2017-01-12 17:18
what happened to `plugin`?

```python
2017-01-12 17:16:57.333318|ERROR   |pyTSon.PluginHost.init|   |Error loading python plugin from C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon\scripts\answercontacts\: Traceback (most recent call last):
                                                                 File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\ts3plugin.py", line 209, in reload
                                                                   cls.modules[base] = importlib.__import__(base)
                                                                 File "<frozen importlib._bootstrap>", line 1055, in __import__
                                                                 File "<frozen importlib._bootstrap>", line 986, in _gcd_import
                                                                 File "<frozen importlib._bootstrap>", line 969, in _find_and_load
                                                                 File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
                                                                 File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
                                                                 File "<frozen importlib._bootstrap_external>", line 665, in exec_module
                                                                 File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
                                                                 File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\answercontacts\__init__.py", line 1, in <module>
                                                                   from ts3plugin import plugin
                                                               ImportError: cannot import name 'plugin'
```

**Comment by pathmann** [comment] 2017-01-12 17:24
There was never a class called 'plugin' in that module. It's still 'ts3plugin' (module + class).

**Comment by Bluscream** [comment] 2017-01-12 17:27
Yeah it seems I fucked it up when regex replacing :( Sorry

**Comment by Bluscream** [comment] 2017-01-12 19:14
Okay so after some testing I can confirm that this bug is fixed for me now.

Some stuff that is still concerning me: 
- `1/12/2017 19:10:35	pytsonui.retrieveWidgets.	Error	Error loading iconpack: startswith first arg must be bytes or a tuple of bytes, not str`
- `1/12/2017 19:10:35	pyTSon.ConfigurationDialog.setupList	Error	Error loading iconpack: startswith first arg must be bytes or a tuple of bytes, not str`

**Closed** 2017-01-12 19:37 UTC
