### ISSUE TITLE
[1.2.0 | Windows | 32bit, 64bit] Exception: Could not find uifile

### ISSUE THREAD

**Issue by BradyThe** [pathmann/pyTSon#66] opened 2017-05-12 20:13 UTC
Hey Thomas,

after installing the update I am unable to open the settings menu. Following error occurs. Tested in three different environments. How should I proceed? Thanks!

>pyTSon	Error	Calling onMenuItemEvent failed with error "Error calling method
Traceback (most recent call last):
File "C:/Users/Brady/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 378, in callMethod return meth(*args)
File "C:/Users/Brady/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 626, in onMenuItemEvent cls.configure()
File "C:/Users/Brady/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 368, in configure cls.confdlg = ConfigurationDialog(cls.cfg, cls, mainwindow)
File "C:/Users/Brady/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\config.py", line 92, in __init__ raise e
File "C:/Users/Brady/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\config.py", line 84, in __init__ widgets=self.CONF_WIDGETS)
File "C:/Users/Brady/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\__init__.py", line 295, in setupUi raise Exception("Could not find uifile")
Exception: Could not find uifile

**Comment by pathmann** [comment] 2017-05-12 22:07
Duplicate of #63.

There was a bug in the bundle script (Fixed with 6e0119f).

Either move the file pyTSon-configdialog.ui from ressources/ui to ressources or redownload the release (I uploaded a new one).

**Closed by pathmann** 2017-05-12 22:07 UTC

**Comment by BradyThe** [comment] 2017-05-12 22:41
I should have looked into the closed issues, sorry!

**Comment by pathmann** [comment] 2017-05-13 07:26
It's alright, I closed both issues at the same time :)
